[global]
showWarningOnDirectExecution = true


[server]
headless = true
enableXsrfProtection=false
enableCORS = false
enableWebsocketCompression=false
port = 80


[browser]
serverAddress = "0.0.0.0"
serverPort = 80
gatherUsageStats = false
